mysqlsocialCREATE TABLE IF NOT EXISTS vacances (
    id INT AUTO_INCREMENT PRIMARY KEY,
    matricule VARCHAR(20),
    nom VARCHAR(100),
    nom_original VARCHAR(100),
    prenom VARCHAR(100),
    date_naissance DATE,
    lieu_naissance VARCHAR(100),
    adresse VARCHAR(255),
    fonction VARCHAR(100),
    lieu_travail VARCHAR(100),
    telephone VARCHAR(20),
    compte_bancaire VARCHAR(50),
    categorie VARCHAR(50),
    periode_enseignement VARCHAR(100),
    destination VARCHAR(100),
    accompagnant1_nom VARCHAR(100),
    accompagnant1_naissance DATE,
    accompagnant1_lien VARCHAR(50),
    accompagnant1_notes VARCHAR(100),
    accompagnant2_nom VARCHAR(100),
    accompagnant2_naissance DATE,
    accompagnant2_lien VARCHAR(50),
    accompagnant2_notes VARCHAR(100),
    accompagnant3_nom VARCHAR(100),
    accompagnant3_naissance DATE,
    accompagnant3_lien VARCHAR(50),
    accompagnant3_notes VARCHAR(100),
    accompagnant4_nom VARCHAR(100),
    accompagnant4_naissance DATE,
    accompagnant4_lien VARCHAR(50),
    accompagnant4_notes VARCHAR(100)
);
